<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:sch="http://www.lockstd.org/a" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.lockstd.org/a" targetNamespace="http://www.lockstd.org/a">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:a="http://www.lockstd.org/a"
			elementFormDefault="qualified" targetNamespace="http://www.lockstd.org/a">
			<element name="aaRequest" />
		</schema>
	</wsdl:types>
	<wsdl:message name="aaRequest">
		<wsdl:part element="tns:aaRequest" name="aaRequest"></wsdl:part>
	</wsdl:message>
	<wsdl:portType name="SayHello">
		<wsdl:operation name="aa">
			<wsdl:input message="tns:aaRequest" name="aaRequest"></wsdl:input>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SayHelloSoap11" type="tns:SayHello">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="aa">
			<soap:operation soapAction="" />
			<wsdl:input name="aaRequest">
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="SayHelloService">
		<wsdl:port binding="tns:SayHelloSoap11" name="SayHelloSoap11">
			<soap:address location="http://localhost:8080/airline-web-app/ws/sayHelloService/" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>